name: CI workflow
on:
    push:
        branches:
            - master

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: before_script
              run: |
                php composer.phar install --no-scripts --no-progress
            - name: Run test
              run: |
                bin/phpunit tests/Unit
                bin/phpunit tests/Integration
                php vendor/bin/behat
