name: CI workflow
on:
    push:
        branches:
            - master

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: action/checkout@v2
            - name: before_script
              run: |
                composer install
            - name: Run test
              run: |
                bin/phpunit tests/Unit
                bin/phpunit tests/Integration
                php vendor/bin/behat