name: CI workflow
on:
    push:
        branches:
            - master

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: before_script
              run: |
                apt update && apt install -y git
                curl --show-error --silent https://getcomposer.org/installer | php
                php composer.phar install --no-scripts --no-progress

            