name: CI workflow
on:
    push:
        branches:
            - master

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: before_script
              uses: docker://composer:latest
              with:
                args: install
            - name: Run test
              run: |
                bin/phpunit tests/Unit
                bin/phpunit tests/Integration
                php vendor/bin/behat
